apiVersion: v1
kind: Secret
metadata:
  name: k8s-agent-token-secret
type: Opaque
data:
  agentToken: {{ required "A valid CloudXray K8s agent token is required" .Values.general.agentToken | b64enc | quote }}
