apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudxray-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudxray-cr-binding
subjects:
- kind: ServiceAccount
  name: cloudxray-sa
  namespace: cloudxray
roleRef:
  kind: ClusterRole
  name: cloudxray-role 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudxray-sa
